;;; http-status.lisp

(in-package :nancy)

(defvar *http-keyword-status* (make-hash-table))

(macrolet ((define-keyword-status (keyword status-code)
             `(setf (gethash ,keyword *http-keyword-status*) ,status-code)))
  (define-keyword-status :continue 100)
  (define-keyword-status :switching-protocols 101)
  (define-keyword-status :ok 200)
  (define-keyword-status :created 201)
  (define-keyword-status :accepted 202)
  (define-keyword-status :non-authoritative-information 203)
  (define-keyword-status :no-content 204)
  (define-keyword-status :reset-content 205)
  (define-keyword-status :partial-content 206)
  (define-keyword-status :multi-status 207)
  (define-keyword-status :multiple-choices 300)
  (define-keyword-status :moved-permanently 301)
  (define-keyword-status :moved-temporarily 302)
  (define-keyword-status :see-other 303)
  (define-keyword-status :not-modified 304)
  (define-keyword-status :use-proxy 305)
  (define-keyword-status :temporary-redirect 307)
  (define-keyword-status :bad-request 400)
  (define-keyword-status :authorization-required 401)
  (define-keyword-status :payment-required 402)
  (define-keyword-status :forbidden 403)
  (define-keyword-status :not-found 404)
  (define-keyword-status :method-not-allowed 405)
  (define-keyword-status :not-acceptable 406)
  (define-keyword-status :proxy-authentication-required 407)
  (define-keyword-status :request-time-out 408)
  (define-keyword-status :conflict 409)
  (define-keyword-status :gone 410)
  (define-keyword-status :length-required 411)
  (define-keyword-status :precondition-failed 412)
  (define-keyword-status :request-entity-too-large 413)
  (define-keyword-status :request-uri-too-large 414)
  (define-keyword-status :unsupported-media-type 415)
  (define-keyword-status :requested-range-not-satisfiable 416)
  (define-keyword-status :expectation-failed 417)
  (define-keyword-status :failed-dependency 424)
  (define-keyword-status :internal-server-error 500)
  (define-keyword-status :not-implemented 501)
  (define-keyword-status :bad-gateway 502)
  (define-keyword-status :service-unavailable 503)
  (define-keyword-status :gateway-time-out 504)
  (define-keyword-status :version-not-supported 505))

(defun http-keyword-status (keyword)
  "Retrieve numeric status code for keyword."
  (gethash keyword *http-keyword-status*))
